
(window.callback73346=window.callback73346||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(73346);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(73720);(function(){$('#ATList').attr({"ms.cmptyp":"rightrail","ms.cmpnm":"sellang","ms.scn":"1.2","ms.scvalue":"prodlang"});var i=0;$("#ATList ul li").each(function(){i=i+1;var ti=$("a",$(this)).text().trim();$(this).attr({"ms.title":ti,"ms.interactiontype":"1","ms.index":i,"ms.languageid":ti});});var ads=$('#thinColumn .adWrapper a');var tads=$(ads).children('img').attr("alt");$('#thinColumn .adWrapper a').attr({'ms.pgarea':'rihtnav','ms.cmpgrp':'body','ms.cmptyp':'rightrail','ms.cmpnm':'ads','ms.title':tads,'ms.interactiontype':'1'});$(Bootstrapper.TMDL._domselectors.KB_VIEW_PROD).each(function(){$(this).attr({'ms.cmpgrp':'link','ms.cmptyp':'link','ms.cmpnm':'prdlink','ms.title':$(this).text().trim().toLowerCase(),'ms.interactiontype':'1'});});var expandAll=$('#expandAll');var texpn=$(expandAll).attr("id");$(expandAll).attr({'ms.pgarea':'body','ms.cmpgrp':'control','ms.cmptyp':'link','ms.cmpnm':'expandAll','ms.title':texpn,'ms.interactiontype':'1'});var collapseAll=$('#collapseAll');var tcol=$(collapseAll).attr("id");$(collapseAll).attr({'ms.pgarea':'body','ms.cmpgrp':'control','ms.cmptyp':'link','ms.cmpnm':'collapseAll','ms.title':tcol,'ms.interactiontype':'1'});$("#kb_section h2,.kbSurvey h2").click(function(event){var evt=event||window.event;var e,check;if(evt){try{e=evt.srcElement||evt.target;check=MscomIsInList(e.tagName);while(e.tagName&&check===0){e=e.parentElement||e.parentNode;if(e.tagName){check=MscomIsInList(e.tagName);}}}catch(err){}
var intrn=14;if($(this).hasClass('kb_tabs_toggle_closed')){intrn=15;}
var ti=$(this).text().trim();if(ti.length<1){ti=$(this).parent().text().trim();}
if(check===0){MscomCustomEvent("ms.cmpgrp=body","ms.cmpnm=acrd","ms.cmptyp=control","ms.title="+ti,"ms.interactiontype="+intrn);}else{$(this).attr({"ms.cmpnm":"acrd","ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":intrn});}}});$("#kb_section a,.kbSurvey a").each(function(){if($(this).not("[ms\\.title]"))
{var t=$(this).text().trim();$(this).attr({"ms.cmpnm":"acrd","ms.cmptyp":"link","ms.title":t,"ms.interactiontype":"1"});}});})();}catch(e){Bootstrapper.reportException(e);}});});Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(75887);var submitBtn=$('.NAVBUTTON').get(0);var surveyId=$('.SURVEYSECTION').attr('id').split("_");surveyId=surveyId[surveyId.length-1];function triggerCustomEvt(){var i=1;$('.CHOICEROW input:checked').each(function(){queTxt=$(this).parents('div.QUESTIONCONTAINER').children("div.QUESTIONTEXT").text().trim();queTxt="Q"+(i++)+"."+queTxt;ansTxt=$(this).parent().next(".ANSWERTEXT").text();MscomCustomEvent('ms.cmpgrp=body','ms.interactiontype=19','ms.scnum='+surveyId,'ms.svi='+surveyId,'ms.svq='+queTxt,'ms.scn='+queTxt,'ms.scvalue='+ansTxt,'ms.sva='+ansTxt);});var txtBxQues=$('a.QUESTIONTEXT',$('#SURVEYQUESTION_12617')).text().trim();var txtBxval=$('.ANSWERBOX',$('#SURVEYQUESTION_12617')).val();if(txtBxval.length>0){MscomCustomEvent('ms.cmpgrp=body','ms.interactiontype=19','ms.scnum='+surveyId,'ms.svi='+surveyId,'ms.svq='+txtBxQues,'ms.scn='+txtBxQues,'ms.scvalue='+txtBxval,'ms.svv='+txtBxval);}}
if(navigator.appVersion.indexOf("MSIE")!=-1){Bootstrapper.unobtrusiveAddEvent(submitBtn,"onclick",function(submitBtn){return function(){triggerCustomEvt();$(this).attr({'ms.cmpnm':'submit','ms.cmptyp':'button','ms.interactiontype':'9','ms.scnum':surveyId,'ms.svi':surveyId});};}(submitBtn));}else{Bootstrapper.unobtrusiveAddEvent(submitBtn,"onmousedown",function(submitBtn){return function(){triggerCustomEvt();$(this).attr({'ms.cmpnm':'submit','ms.cmptyp':'button','ms.interactiontype':'9','ms.scnum':surveyId,'ms.svi':surveyId});};}(submitBtn));}
$('input[type!="button"]').each(function(){var ele=this;Bootstrapper.unobtrusiveAddEvent(ele,"onmousedown",function(ele){return function(){var event=(navigator.appVersion.indexOf("MSIE")!=-1)?"click":"mousedown";if(document.body){if(document.body.removeEventListener){document.body.removeEventListener(event,window.MscomProcessClick,0);}
else if(document.body.detachEvent){document.body.detachEvent("onclick",window.MscomProcessClick);}}
window.setTimeout(MscomsetEvents,100);};}(ele));});;}catch(e){Bootstrapper.reportException(e);}});;